openapi: 3.2.0
info:
  title: 701x API V1 Comment Master Controller Basic API
  description: 701x API
  version: v1
tags:
- name: CommentMasterControllerBasic
paths:
  /CommentMasterControllerBasic/Get/{id}:
    get:
      tags:
      - CommentMasterControllerBasic
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Comment_Master'
            application/json:
              schema:
                $ref: '#/components/schemas/Comment_Master'
            text/json:
              schema:
                $ref: '#/components/schemas/Comment_Master'
      summary: Get comment master controller basic get by id
      x-summary-source: derived
      operationId: getCommentMasterControllerBasicGetById
      x-operation-id-source: derived
  /CommentMasterControllerBasic/GetByFilter:
    get:
      tags:
      - CommentMasterControllerBasic
      parameters:
      - name: top
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: WOId
        in: query
        schema:
          type:
          - string
          - 'null'
          format: uuid
      - name: LessThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: LessThenUpdatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenUpdatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: LessThenDeletedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenDeletedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment_Master'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment_Master'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment_Master'
      summary: Get comment master controller basic get by filter
      x-summary-source: derived
      operationId: getCommentMasterControllerBasicGetByFilter
      x-operation-id-source: derived
  /CommentMasterControllerBasic:
    post:
      tags:
      - CommentMasterControllerBasic
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Comment_Master'
          application/json:
            schema:
              $ref: '#/components/schemas/Comment_Master'
          text/json:
            schema:
              $ref: '#/components/schemas/Comment_Master'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Comment_Master'
      responses:
        '200':
          description: Success
      summary: Create comment master controller basic
      x-summary-source: derived
      operationId: postCommentMasterControllerBasic
      x-operation-id-source: derived
  /CommentMasterControllerBasic/{id}:
    put:
      tags:
      - CommentMasterControllerBasic
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Comment_Master'
          application/json:
            schema:
              $ref: '#/components/schemas/Comment_Master'
          text/json:
            schema:
              $ref: '#/components/schemas/Comment_Master'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Comment_Master'
      responses:
        '200':
          description: Success
      summary: Replace comment master controller basic by id
      x-summary-source: derived
      operationId: putCommentMasterControllerBasicById
      x-operation-id-source: derived
    delete:
      tags:
      - CommentMasterControllerBasic
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
      summary: Delete comment master controller basic by id
      x-summary-source: derived
      operationId: deleteCommentMasterControllerBasicById
      x-operation-id-source: derived
components:
  schemas:
    Comment_Master:
      type: object
      properties:
        id:
          type: string
          format: uuid
        legacyId:
          type:
          - string
          - 'null'
        companyId:
          type:
          - string
          - 'null'
          format: uuid
        companySaleId:
          type:
          - string
          - 'null'
          format: uuid
        companyTransferId:
          type:
          - string
          - 'null'
          format: uuid
        companyPurchaseId:
          type:
          - string
          - 'null'
          format: uuid
        contactId:
          type:
          - string
          - 'null'
          format: uuid
        farmId:
          type:
          - string
          - 'null'
          format: uuid
        groupId:
          type:
          - string
          - 'null'
          format: uuid
        farmVirtualFenceId:
          type:
          - string
          - 'null'
          format: uuid
        farmPointOfInterestId:
          type:
          - string
          - 'null'
          format: uuid
        animalId:
          type:
          - string
          - 'null'
          format: uuid
        tagId:
          type:
          - string
          - 'null'
          format: uuid
        logId:
          type:
          - string
          - 'null'
          format: uuid
        feedbackId:
          type:
          - string
          - 'null'
          format: uuid
        woId:
          type:
          - string
          - 'null'
          format: uuid
        saleDayId:
          type:
          - string
          - 'null'
          format: uuid
        saleDayLotId:
          type:
          - string
          - 'null'
          format: uuid
        comment:
          type:
          - string
          - 'null'
        groupCode:
          type:
          - string
          - 'null'
        groupDescription:
          type:
          - string
          - 'null'
        companyDescription:
          type:
          - string
          - 'null'
        farmDescription:
          type:
          - string
          - 'null'
        fenceDescription:
          type:
          - string
          - 'null'
        poiDescription:
          type:
          - string
          - 'null'
        contactDescription:
          type:
          - string
          - 'null'
        transferDescription:
          type:
          - string
          - 'null'
        purchaseDescription:
          type:
          - string
          - 'null'
        saleDescription:
          type:
          - string
          - 'null'
        createdByDate:
          type:
          - string
          - 'null'
          format: date-time
        createdByUserId:
          type:
          - string
          - 'null'
          format: uuid
        createdByName:
          type:
          - string
          - 'null'
        lastUpdatedByDate:
          type:
          - string
          - 'null'
          format: date-time
        lastUpdatedByUserId:
          type:
          - string
          - 'null'
          format: uuid
        lastUpdatedByName:
          type:
          - string
          - 'null'
        inActiveDate:
          type:
          - string
          - 'null'
          format: date-time
        lastSyncEpoch:
          type:
          - integer
          - 'null'
          format: int64
        deleteSyncEpoch:
          type:
          - integer
          - 'null'
          format: int64
        isNew:
          type: boolean
        isUpdate:
          type: boolean
        isDelete:
          type: boolean
        error:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.701x.com/connect/authorize
          tokenUrl: https://login.701x.com/connect/token
          scopes:
            api1: Demo API - full access
