openapi: 3.2.0
info:
  title: 701x API V1 Contact Controller Admin API
  description: 701x API
  version: v1
tags:
- name: ContactControllerAdmin
paths:
  /ContactControllerAdmin/ContactDataByFilter:
    get:
      tags:
      - ContactControllerAdmin
      parameters:
      - name: top
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: CompanyId
        in: query
        schema:
          type: string
          format: uuid
      - name: LessThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: LessThenUpdatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenUpdatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: LessThenDeletedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenDeletedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact_Master'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact_Master'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact_Master'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Get contact controller admin contact data by filter
      x-summary-source: derived
      operationId: getContactControllerAdminContactDataByFilter
      x-operation-id-source: derived
  /ContactControllerAdmin/{id}:
    get:
      tags:
      - ContactControllerAdmin
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Contact_Master'
            application/json:
              schema:
                $ref: '#/components/schemas/Contact_Master'
            text/json:
              schema:
                $ref: '#/components/schemas/Contact_Master'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Get contact controller admin by id
      x-summary-source: derived
      operationId: getContactControllerAdminById
      x-operation-id-source: derived
    put:
      tags:
      - ContactControllerAdmin
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Contact_Master'
          application/json:
            schema:
              $ref: '#/components/schemas/Contact_Master'
          text/json:
            schema:
              $ref: '#/components/schemas/Contact_Master'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Contact_Master'
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Replace contact controller admin by id
      x-summary-source: derived
      operationId: putContactControllerAdminById
      x-operation-id-source: derived
    delete:
      tags:
      - ContactControllerAdmin
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Contact_Master'
            application/json:
              schema:
                $ref: '#/components/schemas/Contact_Master'
            text/json:
              schema:
                $ref: '#/components/schemas/Contact_Master'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Delete contact controller admin by id
      x-summary-source: derived
      operationId: deleteContactControllerAdminById
      x-operation-id-source: derived
  /ContactControllerAdmin:
    post:
      tags:
      - ContactControllerAdmin
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Contact_Master'
          application/json:
            schema:
              $ref: '#/components/schemas/Contact_Master'
          text/json:
            schema:
              $ref: '#/components/schemas/Contact_Master'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Contact_Master'
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Create contact controller admin
      x-summary-source: derived
      operationId: postContactControllerAdmin
      x-operation-id-source: derived
  /ContactControllerAdmin/MassInsert:
    post:
      tags:
      - ContactControllerAdmin
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Contact_Master'
          application/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Contact_Master'
          text/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Contact_Master'
          application/*+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Contact_Master'
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Create contact controller admin mass insert
      x-summary-source: derived
      operationId: postContactControllerAdminMassInsert
      x-operation-id-source: derived
  /ContactControllerAdmin/MassUpdate:
    post:
      tags:
      - ContactControllerAdmin
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Contact_Master'
          application/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Contact_Master'
          text/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Contact_Master'
          application/*+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Contact_Master'
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Create contact controller admin mass update
      x-summary-source: derived
      operationId: postContactControllerAdminMassUpdate
      x-operation-id-source: derived
  /ContactControllerAdmin/MassDelete:
    post:
      tags:
      - ContactControllerAdmin
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Contact_Master'
          application/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Contact_Master'
          text/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Contact_Master'
          application/*+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Contact_Master'
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Create contact controller admin mass delete
      x-summary-source: derived
      operationId: postContactControllerAdminMassDelete
      x-operation-id-source: derived
components:
  schemas:
    Contact_Master:
      type: object
      properties:
        id:
          type: string
          format: uuid
        companyId:
          type:
          - string
          - 'null'
          format: uuid
        userId:
          type:
          - string
          - 'null'
          format: uuid
        organization:
          type:
          - string
          - 'null'
        displayName:
          type:
          - string
          - 'null'
        firstName:
          type:
          - string
          - 'null'
        lastName:
          type:
          - string
          - 'null'
        email:
          type:
          - string
          - 'null'
        phoneNumber:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        website:
          type:
          - string
          - 'null'
        tags:
          type:
          - string
          - 'null'
        mailAddress1:
          type:
          - string
          - 'null'
        mailAddress2:
          type:
          - string
          - 'null'
        mailAddress3:
          type:
          - string
          - 'null'
        mailCountry:
          type:
          - string
          - 'null'
        mailState:
          type:
          - string
          - 'null'
        mailRegion:
          type:
          - string
          - 'null'
        mailZip:
          type:
          - string
          - 'null'
        mailCity:
          type:
          - string
          - 'null'
        longitude:
          type:
          - number
          - 'null'
          format: double
        latitude:
          type:
          - number
          - 'null'
          format: double
        associationCode1:
          type:
          - string
          - 'null'
        associationCode2:
          type:
          - string
          - 'null'
        associationCode3:
          type:
          - string
          - 'null'
        associationCode4:
          type:
          - string
          - 'null'
        associationId1:
          type:
          - string
          - 'null'
        associationId2:
          type:
          - string
          - 'null'
        associationId3:
          type:
          - string
          - 'null'
        associationId4:
          type:
          - string
          - 'null'
        associationMemberId1:
          type:
          - string
          - 'null'
        associationMemberId2:
          type:
          - string
          - 'null'
        associationMemberId3:
          type:
          - string
          - 'null'
        associationMemberId4:
          type:
          - string
          - 'null'
        legacyId:
          type:
          - string
          - 'null'
        salesRep:
          type:
          - string
          - 'null'
        createdByDate:
          type:
          - string
          - 'null'
          format: date-time
        createdByUserId:
          type:
          - string
          - 'null'
          format: uuid
        createdByName:
          type:
          - string
          - 'null'
        lastUpdatedByDate:
          type:
          - string
          - 'null'
          format: date-time
        lastUpdatedByUserId:
          type:
          - string
          - 'null'
          format: uuid
        lastUpdatedByName:
          type:
          - string
          - 'null'
        inActiveDate:
          type:
          - string
          - 'null'
          format: date-time
        lastSyncEpoch:
          type:
          - integer
          - 'null'
          format: int64
        deleteSyncEpoch:
          type:
          - integer
          - 'null'
          format: int64
        isNew:
          type: boolean
        isUpdate:
          type: boolean
        isDelete:
          type: boolean
        error:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.701x.com/connect/authorize
          tokenUrl: https://login.701x.com/connect/token
          scopes:
            api1: Demo API - full access
