openapi: 3.2.0
info:
  title: 701x API V1 Animal Data Birth API
  description: 701x API
  version: v1
tags:
- name: AnimalDataBirth
paths:
  /AnimalDataBirth/AnimalDataBirthByFilter:
    get:
      tags:
      - AnimalDataBirth
      parameters:
      - name: top
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: orderBy
        in: query
        schema:
          type:
          - string
          - 'null'
      - name: offset
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: fetch
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: CompanyId
        in: query
        schema:
          type: string
          format: uuid
      - name: AnimalId
        in: query
        schema:
          type:
          - string
          - 'null'
          format: uuid
      - name: AssociationId
        in: query
        schema:
          type:
          - string
          - 'null'
      - name: RegistrationNumber
        in: query
        schema:
          type:
          - string
          - 'null'
      - name: isShared
        in: query
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Data_Birth'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Data_Birth'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Data_Birth'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Get animal data birth animal data birth by filter
      x-summary-source: derived
      operationId: getAnimalDataBirthAnimalDataBirthByFilter
      x-operation-id-source: derived
  /AnimalDataBirth/GetAllChanges:
    get:
      tags:
      - AnimalDataBirth
      parameters:
      - name: lastSynced
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: companyId
        in: query
        schema:
          type: string
          format: uuid
      - name: includeShared
        in: query
        schema:
          type: boolean
          default: false
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/SyncingRequestParams'
          application/json:
            schema:
              $ref: '#/components/schemas/SyncingRequestParams'
          text/json:
            schema:
              $ref: '#/components/schemas/SyncingRequestParams'
          application/*+json:
            schema:
              $ref: '#/components/schemas/SyncingRequestParams'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BirthData'
            application/json:
              schema:
                $ref: '#/components/schemas/BirthData'
            text/json:
              schema:
                $ref: '#/components/schemas/BirthData'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Get animal data birth get all changes
      x-summary-source: derived
      operationId: getAnimalDataBirthGetAllChanges
      x-operation-id-source: derived
    post:
      tags:
      - AnimalDataBirth
      parameters:
      - name: lastSynced
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: companyId
        in: query
        schema:
          type: string
          format: uuid
      - name: includeShared
        in: query
        schema:
          type: boolean
          default: false
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/SyncingRequestParams'
          application/json:
            schema:
              $ref: '#/components/schemas/SyncingRequestParams'
          text/json:
            schema:
              $ref: '#/components/schemas/SyncingRequestParams'
          application/*+json:
            schema:
              $ref: '#/components/schemas/SyncingRequestParams'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BirthData'
            application/json:
              schema:
                $ref: '#/components/schemas/BirthData'
            text/json:
              schema:
                $ref: '#/components/schemas/BirthData'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Create animal data birth get all changes
      x-summary-source: derived
      operationId: postAnimalDataBirthGetAllChanges
      x-operation-id-source: derived
  /AnimalDataBirth/{id}:
    get:
      tags:
      - AnimalDataBirth
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Animal_Data_Birth'
            application/json:
              schema:
                $ref: '#/components/schemas/Animal_Data_Birth'
            text/json:
              schema:
                $ref: '#/components/schemas/Animal_Data_Birth'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Get animal data birth by id
      x-summary-source: derived
      operationId: getAnimalDataBirthById
      x-operation-id-source: derived
  /AnimalDataBirth/Put/{id}:
    put:
      tags:
      - AnimalDataBirth
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Animal_Data_Birth'
          application/json:
            schema:
              $ref: '#/components/schemas/Animal_Data_Birth'
          text/json:
            schema:
              $ref: '#/components/schemas/Animal_Data_Birth'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Animal_Data_Birth'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Animal_Data_Birth'
            application/json:
              schema:
                $ref: '#/components/schemas/Animal_Data_Birth'
            text/json:
              schema:
                $ref: '#/components/schemas/Animal_Data_Birth'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Replace animal data birth put by id
      x-summary-source: derived
      operationId: putAnimalDataBirthPutById
      x-operation-id-source: derived
  /AnimalDataBirth/MassUpdate:
    post:
      tags:
      - AnimalDataBirth
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Data_Birth'
          application/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Data_Birth'
          text/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Data_Birth'
          application/*+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Data_Birth'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Data_Birth'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Data_Birth'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Data_Birth'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Create animal data birth mass update
      x-summary-source: derived
      operationId: postAnimalDataBirthMassUpdate
      x-operation-id-source: derived
components:
  schemas:
    SyncingTableRequestParams:
      type: object
      properties:
        tableName:
          type:
          - string
          - 'null'
        dateTimeOffset:
          type:
          - string
          - 'null'
          format: date-time
        lastSyncEpochMs:
          type:
          - integer
          - 'null'
          format: int64
          readOnly: true
      additionalProperties: false
    SyncingRequestParams:
      type: object
      properties:
        syncingTableRequestParams:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/SyncingTableRequestParams'
      additionalProperties: false
    DateOnly:
      type: object
      properties:
        year:
          type: integer
          format: int32
          readOnly: true
        month:
          type: integer
          format: int32
          readOnly: true
        day:
          type: integer
          format: int32
          readOnly: true
        dayOfWeek:
          $ref: '#/components/schemas/DayOfWeek'
        dayOfYear:
          type: integer
          format: int32
          readOnly: true
        dayNumber:
          type: integer
          format: int32
          readOnly: true
      additionalProperties: false
    DayOfWeek:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      type: integer
      format: int32
    Animal_Data_Birth:
      type: object
      properties:
        id:
          type: string
          format: uuid
        companyId:
          type:
          - string
          - 'null'
          format: uuid
        animalId:
          type:
          - string
          - 'null'
          format: uuid
        memberNumber:
          type:
          - string
          - 'null'
        associationCode:
          type:
          - string
          - 'null'
        registrationNumber:
          type:
          - string
          - 'null'
        usdaNumber:
          type:
          - string
          - 'null'
        workOrderNumber:
          type:
          - string
          - 'null'
        contemporaryGroup:
          type:
          - string
          - 'null'
        managmentGroup:
          type:
          - string
          - 'null'
        subContemporaryGroup:
          type:
          - string
          - 'null'
        preContemporaryGroup:
          type:
          - string
          - 'null'
        numberOfContemps:
          type:
          - integer
          - 'null'
          format: int32
        rankInContempGroup:
          type:
          - integer
          - 'null'
          format: int32
        animalSex:
          type:
          - string
          - 'null'
        birthDate:
          type:
          - string
          - 'null'
          format: date-time
        dateOfBirth:
          $ref: '#/components/schemas/DateOnly'
        birthWeight:
          type:
          - number
          - 'null'
          format: double
        birthWeightAdj:
          type:
          - number
          - 'null'
          format: double
        birthWeightRatio:
          type:
          - number
          - 'null'
          format: double
        calvingEase:
          type:
          - number
          - 'null'
          format: double
        twinCode:
          type:
          - string
          - 'null'
        calfVigor:
          type:
          - integer
          - 'null'
          format: int32
        breedingType:
          type:
          - string
          - 'null'
        recipientDamRegistration:
          type:
          - string
          - 'null'
        recipientDamAnimalTattoo:
          type:
          - string
          - 'null'
        ageOfDam:
          type:
          - integer
          - 'null'
          format: int32
        embryoFlushDate:
          type:
          - string
          - 'null'
          format: date-time
        embryoTransferDate:
          type:
          - string
          - 'null'
          format: date-time
        damUdderScore:
          type:
          - number
          - 'null'
          format: double
        damTeatScore:
          type:
          - number
          - 'null'
          format: double
        damTemperScore:
          type:
          - number
          - 'null'
          format: double
        calvingSeason:
          type:
          - integer
          - 'null'
          format: int32
        createdByDate:
          type:
          - string
          - 'null'
          format: date-time
        createdByUserId:
          type:
          - string
          - 'null'
          format: uuid
        lastUpdatedByDate:
          type:
          - string
          - 'null'
          format: date-time
        lastUpdatedByUserId:
          type:
          - string
          - 'null'
          format: uuid
        inActiveDate:
          type:
          - string
          - 'null'
          format: date-time
        lastSyncEpoch:
          type:
          - integer
          - 'null'
          format: int64
        deleteSyncEpoch:
          type:
          - integer
          - 'null'
          format: int64
        isShared:
          type:
          - boolean
          - 'null'
        isNew:
          type: boolean
        isUpdate:
          type: boolean
        isDelete:
          type: boolean
        error:
          type:
          - string
          - 'null'
      additionalProperties: false
    BirthData:
      type: object
      properties:
        animalDataBirthInserted:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Animal_Data_Birth'
        animalDataBirthUpdated:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Animal_Data_Birth'
        animalDataBirthDeleted:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Animal_Data_Birth'
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.701x.com/connect/authorize
          tokenUrl: https://login.701x.com/connect/token
          scopes:
            api1: Demo API - full access
