openapi: 3.2.0
info:
  title: 701x API V1 Embryo Tank Controller Basic API
  description: 701x API
  version: v1
tags:
- name: EmbryoTankControllerBasic
paths:
  /EmbryoTankControllerBasic/EmbryoDataByFilter:
    get:
      tags:
      - EmbryoTankControllerBasic
      parameters:
      - name: top
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: orderBy
        in: query
        schema:
          type:
          - string
          - 'null'
      - name: offset
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: fetch
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: CompanyId
        in: query
        schema:
          type: string
          format: uuid
      - name: FarmId
        in: query
        schema:
          type:
          - string
          - 'null'
          format: uuid
      - name: LessThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: LessThenUpdatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenUpdatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: LessThenDeletedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenDeletedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: SearchString
        in: query
        schema:
          type:
          - string
          - 'null'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Embryo_Tank'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Embryo_Tank'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Embryo_Tank'
      summary: Get embryo tank controller basic embryo data by filter
      x-summary-source: derived
      operationId: getEmbryoTankControllerBasicEmbryoDataByFilter
      x-operation-id-source: derived
  /EmbryoTankControllerBasic/{id}:
    get:
      tags:
      - EmbryoTankControllerBasic
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Embryo_Tank'
            application/json:
              schema:
                $ref: '#/components/schemas/Embryo_Tank'
            text/json:
              schema:
                $ref: '#/components/schemas/Embryo_Tank'
      summary: Get embryo tank controller basic by id
      x-summary-source: derived
      operationId: getEmbryoTankControllerBasicById
      x-operation-id-source: derived
  /EmbryoTankControllerBasic/MassInsert:
    post:
      tags:
      - EmbryoTankControllerBasic
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Embryo_Tank'
          application/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Embryo_Tank'
          text/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Embryo_Tank'
          application/*+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Embryo_Tank'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Embryo_Tank'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Embryo_Tank'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Embryo_Tank'
      summary: Create embryo tank controller basic mass insert
      x-summary-source: derived
      operationId: postEmbryoTankControllerBasicMassInsert
      x-operation-id-source: derived
  /EmbryoTankControllerBasic/MassUpdate:
    post:
      tags:
      - EmbryoTankControllerBasic
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Embryo_Tank'
          application/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Embryo_Tank'
          text/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Embryo_Tank'
          application/*+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Embryo_Tank'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Embryo_Tank'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Embryo_Tank'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Embryo_Tank'
      summary: Create embryo tank controller basic mass update
      x-summary-source: derived
      operationId: postEmbryoTankControllerBasicMassUpdate
      x-operation-id-source: derived
  /EmbryoTankControllerBasic/MassDelete:
    post:
      tags:
      - EmbryoTankControllerBasic
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Embryo_Tank'
          application/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Embryo_Tank'
          text/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Embryo_Tank'
          application/*+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Embryo_Tank'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Embryo_Tank'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Embryo_Tank'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Embryo_Tank'
      summary: Create embryo tank controller basic mass delete
      x-summary-source: derived
      operationId: postEmbryoTankControllerBasicMassDelete
      x-operation-id-source: derived
components:
  schemas:
    Embryo_Tank:
      type: object
      properties:
        id:
          type: string
          format: uuid
        companyId:
          type:
          - string
          - 'null'
          format: uuid
        farmId:
          type:
          - string
          - 'null'
          format: uuid
        companyDescription:
          type:
          - string
          - 'null'
        farmDescription:
          type:
          - string
          - 'null'
        tank:
          type:
          - string
          - 'null'
        canister:
          type:
          - string
          - 'null'
        itemNumber:
          type:
          - string
          - 'null'
        damAnimalId:
          type:
          - string
          - 'null'
          format: uuid
        damCode:
          type:
          - string
          - 'null'
        damDescription:
          type:
          - string
          - 'null'
        damCattleNumber:
          type:
          - string
          - 'null'
        damAssociationCode:
          type:
          - string
          - 'null'
        damRegistrationNumber:
          type:
          - string
          - 'null'
        sireAnimalId:
          type:
          - string
          - 'null'
          format: uuid
        sireCode:
          type:
          - string
          - 'null'
        sireDescription:
          type:
          - string
          - 'null'
        sireCattleNumber:
          type:
          - string
          - 'null'
        sireAssociationCode:
          type:
          - string
          - 'null'
        sireRegistrationNumber:
          type:
          - string
          - 'null'
        quantity:
          type:
          - integer
          - 'null'
          format: int32
        estrus_Date:
          type:
          - string
          - 'null'
          format: date-time
        sync_Date:
          type:
          - string
          - 'null'
          format: date-time
        insemination_Date:
          type:
          - string
          - 'null'
          format: date-time
        semonTankId:
          type:
          - string
          - 'null'
          format: uuid
        flush_Date:
          type:
          - string
          - 'null'
          format: date-time
        addedToStorage_Date:
          type:
          - string
          - 'null'
          format: date-time
        removedFromStorage_Date:
          type:
          - string
          - 'null'
          format: date-time
        transferred_Date:
          type:
          - string
          - 'null'
          format: date-time
        transfer_Process:
          type:
          - string
          - 'null'
        legacyId:
          type:
          - string
          - 'null'
        createdByDate:
          type:
          - string
          - 'null'
          format: date-time
        createdByUserId:
          type:
          - string
          - 'null'
          format: uuid
        createdByName:
          type:
          - string
          - 'null'
        lastUpdatedByDate:
          type:
          - string
          - 'null'
          format: date-time
        lastUpdatedByUserId:
          type:
          - string
          - 'null'
          format: uuid
        lastUpdatedByName:
          type:
          - string
          - 'null'
        inActiveDate:
          type:
          - string
          - 'null'
          format: date-time
        lastSyncEpoch:
          type:
          - integer
          - 'null'
          format: int64
        deleteSyncEpoch:
          type:
          - integer
          - 'null'
          format: int64
        isNew:
          type: boolean
        isUpdate:
          type: boolean
        isDelete:
          type: boolean
        error:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.701x.com/connect/authorize
          tokenUrl: https://login.701x.com/connect/token
          scopes:
            api1: Demo API - full access
