openapi: 3.2.0
info:
  title: 701x API V1 Company User API
  description: 701x API
  version: v1
tags:
- name: CompanyUser
paths:
  /CompanyUser/Get/{id}:
    get:
      tags:
      - CompanyUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Company_User'
            application/json:
              schema:
                $ref: '#/components/schemas/Company_User'
            text/json:
              schema:
                $ref: '#/components/schemas/Company_User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Get company user get by id
      x-summary-source: derived
      operationId: getCompanyUserGetById
      x-operation-id-source: derived
  /CompanyUser/AllCompanyUserDataByFilter:
    get:
      tags:
      - CompanyUser
      parameters:
      - name: top
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: orderBy
        in: query
        schema:
          type:
          - string
          - 'null'
      - name: offset
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: fetch
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: CompanyId
        in: query
        schema:
          type:
          - string
          - 'null'
          format: uuid
      - name: LessThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company_User'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company_User'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company_User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Get company user all company user data by filter
      x-summary-source: derived
      operationId: getCompanyUserAllCompanyUserDataByFilter
      x-operation-id-source: derived
  /CompanyUser/RequestsCompanyUserDataByFilter:
    get:
      tags:
      - CompanyUser
      parameters:
      - name: top
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: orderBy
        in: query
        schema:
          type:
          - string
          - 'null'
      - name: offset
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: fetch
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: CompanyId
        in: query
        schema:
          type:
          - string
          - 'null'
          format: uuid
      - name: LessThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company_User'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company_User'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company_User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Get company user requests company user data by filter
      x-summary-source: derived
      operationId: getCompanyUserRequestsCompanyUserDataByFilter
      x-operation-id-source: derived
  /CompanyUser/CompanyUserDataByFilter:
    get:
      tags:
      - CompanyUser
      parameters:
      - name: top
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: orderBy
        in: query
        schema:
          type:
          - string
          - 'null'
      - name: offset
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: fetch
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: CompanyId
        in: query
        schema:
          type:
          - string
          - 'null'
          format: uuid
      - name: LessThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company_User'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company_User'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company_User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Get company user company user data by filter
      x-summary-source: derived
      operationId: getCompanyUserCompanyUserDataByFilter
      x-operation-id-source: derived
  /CompanyUser/UpdateDefaults/{id}:
    put:
      tags:
      - CompanyUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Company_User'
          application/json:
            schema:
              $ref: '#/components/schemas/Company_User'
          text/json:
            schema:
              $ref: '#/components/schemas/Company_User'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Company_User'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Company_User'
            application/json:
              schema:
                $ref: '#/components/schemas/Company_User'
            text/json:
              schema:
                $ref: '#/components/schemas/Company_User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Replace company user update defaults by id
      x-summary-source: derived
      operationId: putCompanyUserUpdateDefaultsById
      x-operation-id-source: derived
  /CompanyUser/AcceptRequest/{id}:
    put:
      tags:
      - CompanyUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Company_User'
          application/json:
            schema:
              $ref: '#/components/schemas/Company_User'
          text/json:
            schema:
              $ref: '#/components/schemas/Company_User'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Company_User'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Company_User'
            application/json:
              schema:
                $ref: '#/components/schemas/Company_User'
            text/json:
              schema:
                $ref: '#/components/schemas/Company_User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Replace company user accept request by id
      x-summary-source: derived
      operationId: putCompanyUserAcceptRequestById
      x-operation-id-source: derived
  /CompanyUser/DeclineRequest/{id}:
    put:
      tags:
      - CompanyUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Company_User'
          application/json:
            schema:
              $ref: '#/components/schemas/Company_User'
          text/json:
            schema:
              $ref: '#/components/schemas/Company_User'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Company_User'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Company_User'
            application/json:
              schema:
                $ref: '#/components/schemas/Company_User'
            text/json:
              schema:
                $ref: '#/components/schemas/Company_User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Replace company user decline request by id
      x-summary-source: derived
      operationId: putCompanyUserDeclineRequestById
      x-operation-id-source: derived
  /CompanyUser/Post:
    post:
      tags:
      - CompanyUser
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Company_User'
          application/json:
            schema:
              $ref: '#/components/schemas/Company_User'
          text/json:
            schema:
              $ref: '#/components/schemas/Company_User'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Company_User'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Company_User'
            application/json:
              schema:
                $ref: '#/components/schemas/Company_User'
            text/json:
              schema:
                $ref: '#/components/schemas/Company_User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Create company user post
      x-summary-source: derived
      operationId: postCompanyUserPost
      x-operation-id-source: derived
  /CompanyUser/Put/{id}:
    put:
      tags:
      - CompanyUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Company_User'
          application/json:
            schema:
              $ref: '#/components/schemas/Company_User'
          text/json:
            schema:
              $ref: '#/components/schemas/Company_User'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Company_User'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Company_User'
            application/json:
              schema:
                $ref: '#/components/schemas/Company_User'
            text/json:
              schema:
                $ref: '#/components/schemas/Company_User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Replace company user put by id
      x-summary-source: derived
      operationId: putCompanyUserPutById
      x-operation-id-source: derived
  /CompanyUser/Delete/{id}:
    delete:
      tags:
      - CompanyUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Company_User'
            application/json:
              schema:
                $ref: '#/components/schemas/Company_User'
            text/json:
              schema:
                $ref: '#/components/schemas/Company_User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Delete company user delete by id
      x-summary-source: derived
      operationId: deleteCompanyUserDeleteById
      x-operation-id-source: derived
components:
  schemas:
    Company_User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        companyId:
          type:
          - string
          - 'null'
          format: uuid
        email:
          type:
          - string
          - 'null'
        invitedToCompany:
          type:
          - string
          - 'null'
        userId:
          type:
          - string
          - 'null'
          format: uuid
        defaultLoadScreen:
          type:
          - string
          - 'null'
        defaultRanch:
          type:
          - string
          - 'null'
        defaultGroup:
          type:
          - string
          - 'null'
        defaultFence:
          type:
          - string
          - 'null'
        defaultBreed:
          type:
          - string
          - 'null'
        defaultBreedDisplay:
          type:
          - string
          - 'null'
        defaultColor:
          type:
          - string
          - 'null'
        defaultVisualTagColor:
          type:
          - string
          - 'null'
        defaultVisualTagLocation:
          type:
          - string
          - 'null'
        defaultEstimatedAge:
          type:
          - string
          - 'null'
        defaultAnimalSort:
          type:
          - string
          - 'null'
        defaultAssociationCode:
          type:
          - string
          - 'null'
        defaultAssociationId:
          type:
          - string
          - 'null'
        starredReports:
          type:
          - string
          - 'null'
        permissionLevel:
          type:
          - integer
          - 'null'
          format: int32
        companyCode:
          type:
          - string
          - 'null'
        companyDescription:
          type:
          - string
          - 'null'
        userFirstName:
          type:
          - string
          - 'null'
        userLastName:
          type:
          - string
          - 'null'
        userOrganization:
          type:
          - string
          - 'null'
        userTitle:
          type:
          - string
          - 'null'
        userEmail:
          type:
          - string
          - 'null'
        userPhone:
          type:
          - string
          - 'null'
        userInActiveDate:
          type:
          - string
          - 'null'
          format: date-time
        createdByDate:
          type:
          - string
          - 'null'
          format: date-time
        createdByUserId:
          type:
          - string
          - 'null'
          format: uuid
        createdByName:
          type:
          - string
          - 'null'
        lastUpdatedByDate:
          type:
          - string
          - 'null'
          format: date-time
        lastUpdatedByUserId:
          type:
          - string
          - 'null'
          format: uuid
        lastUpdatedByName:
          type:
          - string
          - 'null'
        inActiveDate:
          type:
          - string
          - 'null'
          format: date-time
        isNew:
          type: boolean
        isUpdate:
          type: boolean
        isDelete:
          type: boolean
        error:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.701x.com/connect/authorize
          tokenUrl: https://login.701x.com/connect/token
          scopes:
            api1: Demo API - full access
