openapi: 3.2.0
info:
  title: 701x API V1 Stripe Web Hook API
  description: 701x API
  version: v1
tags:
- name: StripeWebHook
paths:
  /webhook:
    post:
      tags:
      - StripeWebHook
      responses:
        '200':
          description: Success
      summary: Create webhook
      x-summary-source: derived
      operationId: postWebhook
      x-operation-id-source: derived
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.701x.com/connect/authorize
          tokenUrl: https://login.701x.com/connect/token
          scopes:
            api1: Demo API - full access
