openapi: 3.2.0
info:
  title: 701x API V1 Animal Turn Out API
  description: 701x API
  version: v1
tags:
- name: AnimalTurnOut
paths:
  /AnimalTurnOut/AnimalTurnOutDataByFilter:
    get:
      tags:
      - AnimalTurnOut
      parameters:
      - name: top
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: orderBy
        in: query
        schema:
          type:
          - string
          - 'null'
      - name: offset
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: fetch
        in: query
        schema:
          type:
          - integer
          - 'null'
          format: int32
      - name: CompanyId
        in: query
        schema:
          type: string
          format: uuid
      - name: FarmId
        in: query
        schema:
          type:
          - string
          - 'null'
          format: uuid
      - name: SireAnimalId
        in: query
        schema:
          type:
          - string
          - 'null'
          format: uuid
      - name: TurnOutId
        in: query
        schema:
          type:
          - string
          - 'null'
          format: uuid
      - name: SeasonId
        in: query
        schema:
          type:
          - string
          - 'null'
          format: uuid
      - name: LessThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenCreatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: LessThenUpdatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenUpdatedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: LessThenDeletedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: GreaterThenDeletedByDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
      - name: isShared
        in: query
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Turn_Out'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Turn_Out'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Turn_Out'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Get animal turn out animal turn out data by filter
      x-summary-source: derived
      operationId: getAnimalTurnOutAnimalTurnOutDataByFilter
      x-operation-id-source: derived
  /AnimalTurnOut/{id}:
    get:
      tags:
      - AnimalTurnOut
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Animal_Turn_Out'
            application/json:
              schema:
                $ref: '#/components/schemas/Animal_Turn_Out'
            text/json:
              schema:
                $ref: '#/components/schemas/Animal_Turn_Out'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Get animal turn out by id
      x-summary-source: derived
      operationId: getAnimalTurnOutById
      x-operation-id-source: derived
    put:
      tags:
      - AnimalTurnOut
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Animal_Turn_Out'
          application/json:
            schema:
              $ref: '#/components/schemas/Animal_Turn_Out'
          text/json:
            schema:
              $ref: '#/components/schemas/Animal_Turn_Out'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Animal_Turn_Out'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Animal_Turn_Out'
            application/json:
              schema:
                $ref: '#/components/schemas/Animal_Turn_Out'
            text/json:
              schema:
                $ref: '#/components/schemas/Animal_Turn_Out'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Replace animal turn out by id
      x-summary-source: derived
      operationId: putAnimalTurnOutById
      x-operation-id-source: derived
    delete:
      tags:
      - AnimalTurnOut
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Animal_Turn_Out'
            application/json:
              schema:
                $ref: '#/components/schemas/Animal_Turn_Out'
            text/json:
              schema:
                $ref: '#/components/schemas/Animal_Turn_Out'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Delete animal turn out by id
      x-summary-source: derived
      operationId: deleteAnimalTurnOutById
      x-operation-id-source: derived
  /AnimalTurnOut:
    post:
      tags:
      - AnimalTurnOut
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Animal_Turn_Out'
          application/json:
            schema:
              $ref: '#/components/schemas/Animal_Turn_Out'
          text/json:
            schema:
              $ref: '#/components/schemas/Animal_Turn_Out'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Animal_Turn_Out'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Animal_Turn_Out'
            application/json:
              schema:
                $ref: '#/components/schemas/Animal_Turn_Out'
            text/json:
              schema:
                $ref: '#/components/schemas/Animal_Turn_Out'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Create animal turn out
      x-summary-source: derived
      operationId: postAnimalTurnOut
      x-operation-id-source: derived
  /AnimalTurnOut/MassInsert:
    post:
      tags:
      - AnimalTurnOut
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Turn_Out'
          application/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Turn_Out'
          text/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Turn_Out'
          application/*+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Turn_Out'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Turn_Out'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Turn_Out'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Turn_Out'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Create animal turn out mass insert
      x-summary-source: derived
      operationId: postAnimalTurnOutMassInsert
      x-operation-id-source: derived
  /AnimalTurnOut/MassUpdate:
    post:
      tags:
      - AnimalTurnOut
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Turn_Out'
          application/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Turn_Out'
          text/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Turn_Out'
          application/*+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Turn_Out'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Turn_Out'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Turn_Out'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Turn_Out'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Create animal turn out mass update
      x-summary-source: derived
      operationId: postAnimalTurnOutMassUpdate
      x-operation-id-source: derived
  /AnimalTurnOut/MassDelete:
    post:
      tags:
      - AnimalTurnOut
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Turn_Out'
          application/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Turn_Out'
          text/json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Turn_Out'
          application/*+json:
            schema:
              type:
              - array
              - 'null'
              items:
                $ref: '#/components/schemas/Animal_Turn_Out'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Turn_Out'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Turn_Out'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal_Turn_Out'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Create animal turn out mass delete
      x-summary-source: derived
      operationId: postAnimalTurnOutMassDelete
      x-operation-id-source: derived
components:
  schemas:
    Animal_Turn_Out:
      type: object
      properties:
        id:
          type: string
          format: uuid
        companyId:
          type:
          - string
          - 'null'
          format: uuid
        farmId:
          type:
          - string
          - 'null'
          format: uuid
        farmVirtualFenceId:
          type:
          - string
          - 'null'
          format: uuid
        turnOutId:
          type:
          - string
          - 'null'
          format: uuid
        seasonId:
          type:
          - string
          - 'null'
          format: uuid
        sireAnimalId:
          type:
          - string
          - 'null'
          format: uuid
        sireCattleNumber:
          type:
          - string
          - 'null'
        sireAssociationCode:
          type:
          - string
          - 'null'
        sireRegistrationNumber:
          type:
          - string
          - 'null'
        sireCode:
          type:
          - string
          - 'null'
        sireDescription:
          type:
          - string
          - 'null'
        steps:
          type:
          - integer
          - 'null'
          format: int32
        distance:
          type:
          - number
          - 'null'
          format: double
        mounts:
          type:
          - integer
          - 'null'
          format: int32
        companyDescription:
          type:
          - string
          - 'null'
        farmDescription:
          type:
          - string
          - 'null'
        farmVirtualFenceDescription:
          type:
          - string
          - 'null'
        turnoutDate:
          type:
          - string
          - 'null'
          format: date-time
        turnInDate:
          type:
          - string
          - 'null'
          format: date-time
        seasonDescription:
          type:
          - string
          - 'null'
        calvingStartDate:
          type:
          - string
          - 'null'
          format: date-time
        calvingEndDate:
          type:
          - string
          - 'null'
          format: date-time
        createdByDate:
          type:
          - string
          - 'null'
          format: date-time
        createdByUserId:
          type:
          - string
          - 'null'
          format: uuid
        createdByName:
          type:
          - string
          - 'null'
        lastUpdatedByDate:
          type:
          - string
          - 'null'
          format: date-time
        lastUpdatedByUserId:
          type:
          - string
          - 'null'
          format: uuid
        lastUpdatedByName:
          type:
          - string
          - 'null'
        inActiveDate:
          type:
          - string
          - 'null'
          format: date-time
        lastSyncEpoch:
          type:
          - integer
          - 'null'
          format: int64
        deleteSyncEpoch:
          type:
          - integer
          - 'null'
          format: int64
        isNew:
          type: boolean
        isUpdate:
          type: boolean
        isDelete:
          type: boolean
        error:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.701x.com/connect/authorize
          tokenUrl: https://login.701x.com/connect/token
          scopes:
            api1: Demo API - full access
