openapi: 3.2.0
info:
  title: 701x API V1 Version API
  description: 701x API
  version: v1
tags:
- name: Version
paths:
  /Version/Get:
    get:
      tags:
      - Version
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Version_Master'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Version_Master'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Version_Master'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Get version get
      x-summary-source: derived
      operationId: getVersionGet
      x-operation-id-source: derived
  /Version/Get/{id}:
    get:
      tags:
      - Version
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Version_Master'
            application/json:
              schema:
                $ref: '#/components/schemas/Version_Master'
            text/json:
              schema:
                $ref: '#/components/schemas/Version_Master'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - API701x
      summary: Get version get by id
      x-summary-source: derived
      operationId: getVersionGetById
      x-operation-id-source: derived
components:
  schemas:
    Version_Master:
      type: object
      properties:
        id:
          type: string
          format: uuid
        versionNumber:
          type:
          - string
          - 'null'
        createdByDate:
          type:
          - string
          - 'null'
          format: date-time
        createdByUserId:
          type:
          - string
          - 'null'
          format: uuid
        createdByName:
          type:
          - string
          - 'null'
        lastUpdatedByDate:
          type:
          - string
          - 'null'
          format: date-time
        lastUpdatedByUserId:
          type:
          - string
          - 'null'
          format: uuid
        lastUpdatedByName:
          type:
          - string
          - 'null'
        inActiveDate:
          type:
          - string
          - 'null'
          format: date-time
        isNew:
          type: boolean
        isUpdate:
          type: boolean
        isDelete:
          type: boolean
        error:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.701x.com/connect/authorize
          tokenUrl: https://login.701x.com/connect/token
          scopes:
            api1: Demo API - full access
